version: '3.8'
name: tinder-for-cousins
services:
  frontend:
    image: hdude4321/tinder-for-cousins-front-end:main
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - backend
  backend:
     image: hdude4321/tinder-for-cousins-back-end:main
     ports:
      - "5000:5000"
     env_file:
      - .env-backend
     depends_on:
      - mongodb
  mongodb:
      image: mongodb/mongodb-community-server:6.0-ubi8
