
name: backend CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: "mongodb://mongodb:27017"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-flask pymongo flask-cors
        if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
    - name: Test with pytest
      run: |
       cd backend
       pytest tests/test_app.py

 