
name: backend CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: "mongodb://mongodb:27017"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-flask pymongo flask-cors
        if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
    - name: Test with pytest
      run: |
       cd backend
       PYTHONPATH=./ pytest tests/test_app.py

  # push_to_registry:
  #   name: Push Docker Image to Docker Hub
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out the repo
  #       uses: actions/checkout@v4

  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v3.0.0
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_TOKEN }}
  #     - name: Extract metadata for Docker
  #       id: meta
  #       uses: docker/metadata-action@v5.3.0
  #       with:
  #         images: hdude4321/tinder-for-cousins-back-end
  #     - name: Build and push Docker Image
  #       uses: docker/build-push-action@v5.1.0
  #       with:
  #         context: ./backend
  #         file: ./backend/Dockerfile
  #         push: true
  #         tags: ${{ steps.meta.outputs.tags }}
  #         labels: ${{ steps.meta.outputs.labels }}
          
